

### Zapisz task do bazy
POST http://localhost:8080/tasks
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
"id": "5",
"name": "test 5",
"description": "Zadanie z TASK2 z gita",
"repositoryPath": "https://github.com/rafal-nowak/task2"
}

<> 2022-01-20T203200.200.json

### przypisz task do usera
POST http://localhost:8080/usertask/assign
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
"userEmail": "stefan@example.com",
"taskId": "5"
}
### Wyslij task do sprawdzenia
POST http://localhost:8080/usertask/run
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "userEmail": "stefan@example.com",
  "taskId": "5"
}
