### login as student
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "email": "rafal@gmail.com",
  "password": "userPass"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}


### login as admin
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "email": "jan@example.com",
  "password": "MyPassword"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}