### login user
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "email": "stefan@example.com",
  "password": "password"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}


### login admin
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "email": "jan@example.com",
  "password": "MyPassword"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}