### get user by email
GET http://localhost:8080/users/jan@example.com
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=

### Encode to Base64 format: jan@example.com:MyPassword
### Result: amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=

### get user by email
GET http://localhost:8080/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic c3RlZmFuQGV4YW1wbGUuY29tOnBhc3N3b3Jk=

###
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=

{
  "email": "rafal@gmail.com",
  "name": "Rafal Nowak",
  "password": "userPass",
  "roles": ["STUDENT"]
}

### get user by id
GET http://localhost:8080/users/62153e676b1e1d4a83869468
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

